#!/bin/bash


#Init : github.com/viyoriya/dmenuTimer

# This script is for dwmblocks

timerFile="/tmp/.timerFile" #move it to ~/.config/ so it will be persisted even after reboot

#timerFile="~/.config/dtimer/.timerFile"

if [ -f $timerFile ]; then
      timer=$(cat $timerFile)
      tmpTime=$(date -d "$timer" +'%H:%M')
      timerSec=$(date +%s -d "$tmpTime")
      now=$(date +%s)
      timeDiff=$(( ($timerSec - $now) / 60 ))
      if [ "$timeDiff" -ge "0" ]; then
            printf " $timeDiff Min"
      else
          notify-send -u low "Timer" "done !!!" -i ~/.config/dtimer/dwm_logo.png
          paplay ~/.config/dtimer/mixkit-happy-bell-alert-601.wav
          rm $timerFile
      fi
fi


